### ISSUE TITLE
Python sub processes for Bash connection

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#10]
## User story
1. As a user
2. I want to establish communication with emba backend processes

## Acceptance criteria
* Python sub-processes are utilised in creating a script that enables this feature.
* A stable and reliable connection is successfully established.

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by VKrishna09** [comment]
Merged into main on 28.04.2021
