### ISSUE TITLE
Redis Setup

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#108]
## User story
1. As a developer
2. I want / need to make sure that inter process communication works in production, so we can monitor multiple emba processes at the same time

## Acceptance criteria
* Redis works
* Channel Layers works

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by diegiesskanne** [comment]
https://github.com/amosproj/amos-ss2021-emba-service/commit/7c9d1590a7bc0aca885c40bb878591b4ecda9776

**Comment by bitans94** [comment]
Closed on 16.06.2021
