### ISSUE TITLE
Redesign reporting dashboard

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#114]
## User story
1. As a developer
2. I want / need to redesign the reporting dashboard
3. In order for it to have the same look and feel as the rest of the UI

## Acceptance criteria
* Have seamless look and feel of the UI in the reporting dashboard

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by VKrishna09** [comment]
closed on 07.07.2021
