### ISSUE TITLE
System load 

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#116]
## User story
1. As a user
2. I want to visualize the system load in the dashboard.

## Acceptance criteria
* This feature should be implemented with the visualization of the system load over the last 24hrs/ week/ month, i.e. schedulers.

## Definition of done
* The feature reports the above-mentioned data on the dashboard as a statistical value
- Code review from peers has been completed and passed
  - Code is fully implemented and commented
  - Adheres to coding guidelines
  - Commits are not squashed
  - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
Closed on 30.6.2021
