### ISSUE TITLE
View generated reports on dashboard

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#117]
## User story
1. As a user
2. I want / need to view the generated reports on the reporting dashboard.

## Acceptance criteria
- [x] Last 10 reports generated needs to be shown in a tab on the reporting dashboard.
- [x] There should be search functionality over all reports generated.
- [x]  When user clicks on any of these reports, a report dashboard should be available (view similar to central dashboard).

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by VKrishna09** [comment]
closed on 07.07.2021
