### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#118]
## User story
1. As a developer
2. I need to be able to restart or continue from the point of stop to carry out the further process. 

## Acceptance criteria
* The processes continue from where it stops or restarts again for a smooth run

## Definition of done
* The above feature is implemented and works perfectly.
- Code review from peers has been completed and passed
  - Code is fully implemented and commented
  - Adheres to coding guidelines
  - Commits are not squashed
  - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by VKrishna09** [comment]
SD says that this task requires a WebSocket which needs some other tickets in addition to this. This will be checked with the client and can be reopened later.

**Comment by VKrishna09** [comment]
As it is partially done, this ticket is reopened. Please refer to the above comment for completeness.

**Comment by ravichandraachanta** [comment]
Partial requirement has been implemented , Couldn't implement websocket to read error log due to time constraint and dependencies existing in the project.
