### ISSUE TITLE
Exploring optimized libraries for sub processes

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#12]
## User story
1. As a developer
2. I need to know the python sub-processes which provide a reliable connection with the backend
3. In order to run external programs on the web services being developed.

## Acceptance criteria
* The selected sub-processes must confirm to open-source MIT license.
* The selected sub-processes should be able to provide a reliable connection with emba backend.

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by VKrishna09** [comment]
Merged into main and raised request for develop branch on 28.04.2021
