### ISSUE TITLE
Expert mode data fields for firmware uploader

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#15]
## User story
1. As a user
2. I want to enter additional information into the firmware uploader
3. In order to provide in-depth information necessary for "Expert mode" users.

## Acceptance criteria
* Following inputs should be implemented in Expert mode:
     * -a [MIPS]       :Architecture of the Linux firmware [MIPS, ARM, x86, x64, PPC] as a dropdown.
     * -c                   :Enable cwe-checker as a checkbox.
     * -x                   :deep extraction
*  Input fields must be implemented as per specifications.
*  There should be graceful error handling in case of wrong/missing inputs
*  It must be compatible with existing emba services. 

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by bitans94** [comment]
scraped
