### ISSUE TITLE
Styling of graphs in EMBA main dashboard

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#155]
## User story
1. As a user
2. I want to have the stylings set for the main dashboard graphs, charts.

## Acceptance criteria
* Stylings should be done in a way it fits in the frame, has a good resolution. 

## Definition of done

- Code review from peers has been completed and passed
  - Code is fully implemented and commented
  - Adheres to coding guidelines
  - Commits are not squashed
  - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
Closed on 7.7.2021
