### ISSUE TITLE
Central Dashboard

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#16]
## User story
1. As a team member I would like to know whether the Central Dashboard requirement with the info displayed as follows

Central dashboard (Aggregated details of all tests):

 

All the infos in an aggregated state (the screenshot is only from an internal massive firmware scan which shows some numbers as example):

 

 

*         Number of firmwares analysed

*         Number of files, directories, binaries

*         Number of CWEs found:

 

=> e.g. https://appstack.bootlab.io/charts-chartjs.html

 

 

*         Top 10 CVEs (CVE 10 upwards) with a short description -> Klick on a CVE to get an overview wich Firmware it is affected

*         Top 10 Linux kernel versions -> klick on a version to get access to all Reports with the kernel version

*         Top 10 Vendors-> klick on a Vendor to get access to all Reports with the kernel version

*         Notfications of new firmwares uploaded for testing and some state info like uploaded, started, finished

*         Top 10 strcpy binaries (highest number of strcpies)

=> Klick on the binary to access the Report from this firmware

 

*         Binary protections

 

 

*         Bill of Material (Software components we identified)

=> top 10 components we have identified

=> klick on one component to get an overview of all reports using this

*         Shellscript issues

 

*         Outdated certificates

 

*         Number of passwords/hashes

*         Add a "upload firmware" button

*         Change to service dashboard with running services and an overview of all analysed scans

 

Reporting dashboard:

Tab with all the reports (from emba)

Search functionality over all reports

 

From every report a dashboard (as the central aggregated dashboard) should be available

=> via this dashboard the emba report is called

## Acceptance criteria
* Based on the client requirement and the reference given 

## Definition of done
* This should be completed by the next sprint 28.04.2021

**Comment by bitans94** [comment]
scraped
