### ISSUE TITLE
Emba uploader 

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#19]
## User story
1. As a team member I would like to know how would you like to work on creating an uploader, UI-based button which uploads the images to the EMBA system.

## Acceptance criteria
* Should meet client requirements
* User friendly, should also be possible to drag and drop images along with uploading from the system files.

## Definition of done
* This should be done by the next sprint 28.04.2021

**Comment by bitans94** [comment]
scraped
