### ISSUE TITLE
Setup Docker project

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#20]
## User story
1. As a user
2. I want to be able to package the application with binaries and related dependencies
3. In order to create, run and deploy containerized applications for emba services.

## Acceptance criteria
* A docker project has to be setup in full working condition.
* All developers should be able to replicate and utilise the setup

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by ashutoshsingh0223** [comment]
- Docker is setup now with required info in docker.md
-  We using docker-compose version 1.27.4 for now

**Comment by VKrishna09** [comment]
Merged into the main file and release tags are published on 28.04.2021
