### ISSUE TITLE
Navigation header

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#22]
## User story
1. As a user
2. I want to navigate between different windows on the frontend services
3. So that I have different functions segregated into separate windows.

## Acceptance criteria
*  A navigation style header to be created.
* This should allow the user to switch views between "Uploader" and "Dashboards"

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by VKrishna09** [comment]
Work done 28.04.2021
