### ISSUE TITLE
Proper EMBA integration

### ISSUE THREAD

**Issue by MaximilianWagner** [amosproj/amos-ss2021-emba-service#25]
## User story
1. As a developer
2. I want to script/setup to independently clone emba
3. In order to make persisting changes on the original EMBA Projekt and keep everything tidy.

## Acceptance criteria
* Cloning and integrating of emba in embark to get the docker running
* Script running atleast on Linux

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by ashutoshsingh0223** [comment]
- Deleted code that was copy-pasted from emba repo while setting up docker
- Make a directory `emba` and clone repo everytime before setting `emark` up
- Update Dockerfile to get installer.sh from inside this emba directory

**Comment by VKrishna09** [comment]
Merged and done on 28.04.2021
