### ISSUE TITLE
Frontend integration

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#29]
## User story
1. As a developer
2. I want / need to merge all the frontend functionalities developed till now
3. In order to develop the web service for emba

## Acceptance criteria
* Every individual functionality is properly working post merging.

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by VKrishna09** [comment]
Completed on 05.05.2021
