### ISSUE TITLE
Django or Flask? 

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#3]
## User story
1. As a team member, I would like to know which framework would SDs like to implement between Django and Flask.

## Acceptance criteria
* Majority SD's agree on the framework which can be handled with ease

## Definition of done
* All members should vote for the best possible framework by the next sprint (21.04.2021)

**Comment by VKrishna09** [comment]
Django has been accepted by the SD's.

**Comment by bitans94** [comment]
Django is decided as the framework of choice.
