### ISSUE TITLE
emba service dashboard

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#36]
## User story
1. As a user
2. I want / need to view statuses of services in the dasboard
3. In order to be informed which processes are running..

## Acceptance criteria
* Create a HTML and style sheets for emba service dashboard.
* Status area maybe implemented within a progress bar
* Status messages to be displayed (also look at emba.log for the details you need):
         - Docker container started
         - Docker container destroyed
         - Report generated
         - More state messages via log directory
                      - Module x of y running
                      - Current module

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by diegiesskanne** [comment]
currently working on service_dashboard_progress branch

**Comment by VKrishna09** [comment]
Changed and completed on 26.05.2021
Additional tag is issue #60. Please refer to the other ticket.
