### ISSUE TITLE
ASGI setup

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#37]
## User story
1. As a user
2. I want / need to read the emba log
3. In order to access status parameters.

## Acceptance criteria
* Read the emba.log file successfully.
* Obtain status information of services (example: docker status, file execution status etc)

 
## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by diegiesskanne** [comment]
I created a new branch for setting up asynchronous socket communication via django channels and hypercorn. My work is still in Progress, so I have to continue this issue in the next sprint [https://github.com/amosproj/amos-ss2021-emba-service/tree/channels_asgi_setup](url)

**Comment by diegiesskanne** [comment]
should be extended to next sprint or splitted into two task 1. asgi setup 2. processing emba log

**Comment by diegiesskanne** [comment]
asgi setup now done

**Comment by bitans94** [comment]
Acceptance criteria satisfied and ticket closed on 12.05.2021
Work on further improvements.
