### ISSUE TITLE
Saving firmware image

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#38]
## User story
1. As a user
2. I want / need  to save the uploaded firmware image

## Acceptance criteria
* Save the uploaded the firmware image on the server instead of the local machine.

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by VKrishna09** [comment]
Completed on 05.05.2021
