### ISSUE TITLE
Web Socket Communication

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#39]
## User story
1. As a developer
2. In order to read and write information from there.

## Acceptance criteria
*Backend should be able to push info through this web socket.

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by ashutoshsingh0223** [comment]
The database(mongoDB) gets created loaded with some historical data during build run of the container
Instead we should try to document/understand what is the structure that is in there.

**Comment by bitans94** [comment]
@Mani1210 kindly update with the real size.

**Comment by bitans94** [comment]
Mani left the project and this ticket is taken up by Jaromir.

**Comment by VKrishna09** [comment]
Completed on 26.05.2021
