### ISSUE TITLE
MongoDB integration

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#41]
## User story
1. As a developer
2. I want / need to have the backend functionalities moved to the database

## Acceptance criteria
* Push firmware metadata into the database

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by ashutoshsingh0223** [comment]
After the call the Michael. I got to know:
1. MongoDB needs to be installed on host
2.  We need to add one more step to our setup documentation
3.  This is the step where user needs to run installer.sh on host before building containers

**Comment by bitans94** [comment]
Ticket closed on 12.05.2021
