### ISSUE TITLE
Queue job from frontend

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#42]
## User story
1. As a user
2. I want / need to view the uploaded firmware images
3. From where I can select it for executing a job

## Acceptance criteria
* A dropdown window that shows uploaded firmware images
*  Sends a request to the backend for queuing the job.

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by VKrishna09** [comment]
Completed on 26.05.2021
