### ISSUE TITLE
Large size file uploader functionality

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#48]
## User story
1. As a developer
2. I need to know the file sizes that are used while uploading the files.

## Acceptance criteria
* Test with large file sizes.
* Come up with a strategy that works irrespective of file size

## Definition of done

- Code review from peers has been completed and passed
    - Code is fully implemented and commented
    - Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
scraped
