### ISSUE TITLE
EMBA Error Handling 

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#49]
## User story
1. As a developer
2. I need to let the user know when emba encounters an error 
3. and propagate the info from Backend to Front End for displaying

## Acceptance criteria
* Read emba log and display the error message to the user

## Definition of done

- Code review from peers has been completed and passed
    - Code is fully implemented and commented
    - Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
Closed on 7.7.2021
