### ISSUE TITLE
Which IDE to use?

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#5]
## User story
1. As a team member I would like to know which IDE SDs would prefer?

## Acceptance criteria
* Ease of working and debugging on the code
* Compatible to all systems and versions
* Coherence in coding style

## Definition of done
* All members should vote for the best possible IDE by the next sprint (21.04.2021)

**Comment by VKrishna09** [comment]
On personal choice, as most of the plugins are available in both IDE's

**Comment by bitans94** [comment]
As per preference between VSCode and Pycharm. Both IDEs have multiple library integrations.
