### ISSUE TITLE
Improving the service dashboard

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#51]
## User story
1. As a developer 
2. I need to read the data from the EMBA backend to display on the dashboard.

## Acceptance criteria
* Functionality as part of emba service dashboard
* Live streaming of data from emba backend to the dashboard

## Definition of done

- Code review from peers has been completed and passed
    - Code is fully implemented and commented
    - Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
Developer left project, so ticket is put back into product backlog.

**Comment by bitans94** [comment]
Closed on 23.6.2021
