### ISSUE TITLE
Documentation of Mongo DB

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#52]
## User story
1. As a developer
2. I need to document the analytics and log files needed in the process of working.

## Acceptance criteria
* Documentation of required info from mongoDB

## Definition of done

- Code review from peers has been completed and passed
    - Code is fully implemented and commented
    - Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
scraped
