### ISSUE TITLE
emba main dashboard

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#58]
## User story
1. As a user
2. I want / need a main dashboard
3. In order to view fancy graphs, charts and other analytics.

## Acceptance criteria
* Create the HTML and style sheets for the main dashboard.
* Try out fancy UI elements to view on the dashboard
* Make sure none of the sensitive data is visible in this dashboard

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by VKrishna09** [comment]
This ticket was completed for the sprint on 23.06.2021, the additional part of this ticket was made into another ticket as a continuation. Refer to ticket #155
