### ISSUE TITLE
CSRF cookie not set

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#59]
## User story
1. As a developer
2. I want / need to solve the bug in the analyze button in the UI

## Acceptance criteria
* Solve the bug in the analyze button

## Definition of done
* Added only after week 5
* The same for all features

**Comment by Vaish1795** [comment]
Fixed the issue for analyse button but this whole thing is a feature to be implemented at the global level at later stages.

**Comment by bitans94** [comment]
We have an interim fix and work towards a concrete solution over the next sprint.
