### ISSUE TITLE
Information on prior experience

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#6]
## User story
1. As a team member I would like to know the area of expertise of every SD so that proper role assignment is possible for smooth functioning of the project.

## Acceptance criteria
* Previous experience and expertise on the subject will be considered

## Definition of done
* All members should decide on this before the next sprint (21.04.2021)

**Comment by bitans94** [comment]
* Frontend: Ravi
* Backend: Maxi, Asutosh
* Python: Mani, Jaromir
