### ISSUE TITLE
Save flag info

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#64]
## User story
1. As a developer
2. I want / need to save the flag information from dashboard in the database

## Acceptance criteria
* Store the flags saved from frontend into MySQL db

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by VKrishna09** [comment]
Completed on 26.05.2021
