### ISSUE TITLE
Alert box

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#67]
## User story
1. As a developer
2. I need to implement the alert box in a separate HTML 

## Acceptance criteria
* Alert box pops up displaying the corresponding message

## Definition of done

- Code review from peers has been completed and passed
    - Code is fully implemented and commented
    - Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
Closed on 23.6.2021
