### ISSUE TITLE
Setup remote server

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#77]
## User story
1. As a developer
2. I want / need to setup a remote server
3. In order to have a common testing environment

## Acceptance criteria
* Remote server setup and working.
* Mysql is setup on the remote server

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by VKrishna09** [comment]
Done on 26.05.2021
