### ISSUE TITLE
Setup Django project

### ISSUE THREAD

**Issue by bitans94** [amosproj/amos-ss2021-emba-service#8]
## User story
1. As a user
2. I want to access modern, well-built web services 
3. In order to run emba without command-line knowledge.

## Acceptance criteria
* A Django project has to be set up successfully with required dependencies.
* Every developer can work with the same project.

## Definition of done
* Code review from peers has been completed and passed 
    - Code is fully implemented and commented
    -  Adheres to coding guidelines
    - Commits are not squashed
    - Code is checked into the repository
* Unit tests for backend have been written and are passing
* Manual performance tests on the browser are passing
* No critical bugs are open

**Comment by diegiesskanne** [comment]
A pull request had been craeted and attached to this ticket

**Comment by VKrishna09** [comment]
Merged and completed on 28.04.2021
