### ISSUE TITLE
Image uploader page refresh

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#86]
## User story
1. As a developer
2. I need to automatically refresh the page after uploading the firmware image.

## Acceptance criteria
* page refreshes automatically instead of manual refresh

## Definition of done

- Code review from peers has been completed and passed
  - Code is fully implemented and commented
  - Adheres to coding guidelines
  - Commits are not squashed
  - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
Closed on 2.06.2021
