### ISSUE TITLE
Opening of new html page upon feature selection from dashboard

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#87]
## User story
1. As a developer 
2. I need to open a new HTML page upon selecting features from the dashboard.

## Acceptance criteria
* New HTML page opens upon clicking a feature from the dashboard

## Definition of done

- Code review from peers has been completed and passed
  - Code is fully implemented and commented
  - Adheres to coding guidelines
  - Commits are not squashed
  - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
Closed on 2.06.2021.
Not merged into Main yet.
