### ISSUE TITLE
Ability to delete firmware image 

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#88]
## User story
1. As a developer
2. I need to delete the uploaded firmware image if it is not used anymore.
3. In order to reduce space in the database.

## Acceptance criteria
* The functioning works successfully

## Definition of done

- Code review from peers has been completed and passed
  - Code is fully implemented and commented
  - Adheres to coding guidelines
  - Commits are not squashed
  - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
Closed on 16.6.2021
