### ISSUE TITLE
search report functionality

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#92]
## User story
1. As a user
2. I want a tab with all the reports (from emba) and search functionality over all reports

## Acceptance criteria
* The feature works and the user should be able to search the reports from EMBA from the dashboard(s) and should be able to search in the uploader section.

## Definition of done

- Code review from peers has been completed and passed
  - Code is fully implemented and commented
  - Adheres to coding guidelines
  - Commits are not squashed
  - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
Create new ticket for search function in uploader.
