### ISSUE TITLE
Reporting dashboard functioning 

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#93]
## User story
1. As a user 
2. I want from every report a dashboard (as the central aggregated dashboard) should be available
=> via this dashboard, the emba report is called

## Acceptance criteria
* The above requirement works and every report is available for access.

## Definition of done

- Code review from peers has been completed and passed
  - Code is fully implemented and commented
  - Adheres to coding guidelines
  - Commits are not squashed
  - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
Closed on 9.06.2021
