### ISSUE TITLE
Redesign of EMBA report 

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#94]
## User story
1. As a user
2. I want the original emba report needs to be re-designed to have the same look and feel as the dashboard

## Acceptance criteria
* Fix and implement the style and format for the reports being downloaded from reporting dashboard.

## Definition of done

- Code review from peers has been completed and passed
  - Code is fully implemented and commented
  - Adheres to coding guidelines
  - Commits are not squashed
  - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
SDs came to the conclusion that this feature needs to be implemented from the client end and the team does not have the required platforms or access.
