### ISSUE TITLE
EMBA Service dashboard for multiple containers 

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#98]
## User story
1. As a developer
2. I want/need to view statuses of services in the dashboard 
3. In order to be informed which processes are running on multiple containers for multiple processes 

## Acceptance criteria
Status area maybe implemented within a progress bar

Status messages to be displayed (also look at emba.log for the details you need):
- Docker container started
- Docker container destroyed
- Report generated
- More state messages via log directory
- Module x of y running
- Current module

Short entry of all firmware analyzed with the possibility to look the web reporter and download the whole report
-Finally, we need the emba HTML report available via the dashboard
-Additionally, the whole log directory should be available as a Zip download

## Definition of done

- Code review from peers has been completed and passed
  - Code is fully implemented and commented
  - Adheres to coding guidelines
  - Commits are not squashed
  - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by diegiesskanne** [comment]
currently working on improve_sd branch
https://github.com/amosproj/amos-ss2021-emba-service/tree/improve_sd

**Comment by bitans94** [comment]
Closed on 23.06.2021
