### ISSUE TITLE
Frontend Styling 

### ISSUE THREAD

**Issue by VKrishna09** [amosproj/amos-ss2021-emba-service#99]
## User story
1. As a developer 
2. I want/need to improve the frontend display with appropriate styling 
3. In order to look better

## Acceptance criteria
* The styling looks good and can easily be understood.

## Definition of done

- Code review from peers has been completed and passed
  - Code is fully implemented and commented
  - Adheres to coding guidelines
  - Commits are not squashed
  - Code is checked into the repository
- Unit tests for backend have been written and are passing
- Manual performance tests on the browser are passing
- No critical bugs are open

**Comment by bitans94** [comment]
Closed on 16.6.2021
